### ISSUE TITLE
(数)识别问题

### ISSUE THREAD

**Issue by giant-takitaro** [BSTluo/koishi-plugin-word-core-grammar-basic#2]
`word add 你好(数) (~:0:(数:1))`此表达式能正常工作，识别出“你好(数)”并输出相应结果
但`word add 1d(数) (~:0:(数:1))`无法识别到1d(数)并输出结果

**Comment by BSTluo** [comment]
嗷嗷，这个问题是因为，词库解析的时候是以这样的逻辑解析的：
1. 判断当前获取到的触发词是否能够触发
2. 如果不能的话，将句子内的at和文字替换从前向后替换为(@)和(数)一次，然后再进行第一步，直到成功或者没有结果

大概的流程就像这样：

你发送了个1d111
词库意识到没有"1d111"这个触发词，尝试从前向后进行替换工作

因为从前向后，1d的1被替换成了(数)
原文变为了(数)d111，词库意识到没有这个触发词，再次尝试从前向后进行替换工作

尝试将111替换为(数)
(数)d(数)，依旧没有结果。词库终止运行

**Comment by BSTluo** [comment]
唔，我在考虑如何修补这样的问题

**Comment by BSTluo** [comment]
唔也许我不应该用句子去匹配词库的触发词，而是用词库的触发词匹配句子？

总之非常感谢你的使用！

**Comment by BSTluo** [comment]
唔然后...如果需要制作这样的指令的话，也许你需要暂时先

word.add (数)d(数) (~:(数:1):(数:2))

**Comment by BSTluo** [comment]
我尝试在word-core的v1.0.7版本修复这个问题，请尝试将word-core与word-core-grammar-bassic更新到最新版进行测试

**Comment by giant-takitaro** [comment]
此问题已在新版本中解决。非常感谢！

**Comment by BSTluo** [comment]
> 此问题已在新版本中解决。非常感谢！

好耶！如果有问题欢迎叫我哦！
